### ISSUE TITLE
could you give me the dataset in this issue plz

### ISSUE THREAD

**Issue by uuko** [bhavika/JoyDivision#2]
could you give me the dataset in this issue plz

**Comment by stevencunggesto** [comment]
could you send me the dataset please ?
on stevencunggesto@gmail.com

thanks a lot

**Comment by Somuncu** [comment]
could you send me the dataset please ?
on enessbabaoglu@gmail.com thanks

**Comment by JefferyLJF1129** [comment]
could you send me the dataset please ?
on 806836035@qq.com thanks

**Comment by liyijing024** [comment]
could you send me the dataset please ?
on yijing.li@unsw.edu.au

**Comment by AicsHwo** [comment]
could you also send me the dataset?
Thank you very much :)
leo.hwo@gmail.com

**Comment by bhavika** [comment]
Thank you for your interest, everyone. I'm sorry, I no longer maintain this project but because I've been getting several requests, I made the dataset public over here - http://bhavikatekwani.me/blog/joydivision.html

**Comment by bhavika** [comment]
> could you also send me the dataset?
> Thank you very much :)
> [leo.hwo@gmail.com](mailto:leo.hwo@gmail.com)

http://bhavikatekwani.me/blog/joydivision.html

**Comment by bhavika** [comment]
> could you give me the dataset in this issue plz

http://bhavikatekwani.me/blog/joydivision.html
